run:
  deadline: 30m
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true

linters:
  enable:
    - goimports
    - gofmt
    - misspell
  disable:
    - errcheck
