apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfiguration
metrics:
  bindAddress: :9091
health:
  healthProbeBindAddress: :9092
leaderElection:
  leaderElect: true
  resourceNamespace: "tsuru-system"