apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "networkapi-ingress-controller.fullname" . }}
  labels:
    {{- include "networkapi-ingress-controller.labels" . | nindent 4 }}
data:
  controller-config.yaml: |-
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfiguration
    metrics:
      bindAddress: :9091
    health:
      healthProbeBindAddress: :9092
    leaderElection:
      leaderElect: true
      resourceNamespace: "{{ .Release.Namespace }}"
  networkapi-config.json: |-
    {{ toJson .Values.networkapi.config | nindent 4}}